AllCops:
  # 継承先のプロジェクトでRuby/Railsのバージョンを設定してください。
  # TargetRubyVersion: x.x
  # TargetRailsVersion: x.x
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

#################### Metrics ###############################
# Metricsの最大値(Max)デフォルト値をやや上げしている。
# Rubocopのデフォルトだと、業務処理を書くには厳しすぎるため上げているが、
# 数字に確たる根拠はない。
# 参考) Rubocopのdefault.yml
# https://raw.githubusercontent.com/bbatsov/rubocop/master/config/default.yml

Metrics/AbcSize:
  Max: 25

# 以下のメソッドはパフォーマンスや可読性の観点からブロック行数が長くても良しと判断し、
# メソッド名で除外設定をしている。
# RailsのRouterよりnamespace/resource/resources
# FactoryGirlのdefine/factory
# Rspecのdescribe/it/feature/context/shared_context
Metrics/BlockLength:
  CountComments: false
  ExcludedMethods:
    - namespace
    - resource
    - resources
    - task
    - define
    - factory
    - describe
    - it
    - feature
    - context
    - shared_context
    - scenario

Metrics/BlockNesting:
  CountBlocks: false

Metrics/ClassLength:
  CountComments: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/ModuleLength:
  CountComments: false

Metrics/ParameterLists:
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 15

#################### Layout ###########################

# Caseに対してWhenをインデントしないこと。
Layout/CaseIndentation:
  IndentOneStep: false

# CommentIndentationはシャープのインデント揃えをチェックするが、
# 処理をコメントアウトした場合には処理自体のインデントを揃えた方が綺麗な場合があるためOFF。
Layout/CommentIndentation:
  Enabled: false

# メソッドチェーンを書く際、ドットは次の行の先頭に書くこと。
# irbやpryで実行しづらいデメリットはあるが、この方が可読性が高くコメントアウトもしやすいため。
Layout/DotPosition:
  EnforcedStyle: leading

# 演算子の前後には半角スペースを入れること。
Layout/SpaceAroundOperators:
  AllowForAlignment: true

#################### Style ###########################

# 日本人向けプロダクトで日本語コメント禁止は厳しすぎるので。
# また、sdocでYARD形式のコメントを書くため記号を許容したい。
Style/AsciiComments:
  Enabled: false

# if文の中で代入する書き方と、if文の戻り値で代入する書き方のどちらも許容する。
Style/ConditionalAssignment:
  Enabled: false

# 自作クラスには出来るだけコメントを書いて欲しい。
# Railsのように規約によってある程度クラスの意味はわかる場合、
# 親クラスに :nodoc: all とコメントを入れる事でこの警告は消せます。
Style/Documentation:
  Enabled: true

# 文字列のフォーマットは、format/sprintf/percentで行うこと。
Style/FormatString:
  SupportedStyles:
    - format
    - sprintf
    - percent

# ハッシュのキー指定方法はruby1.9の文法を利用し、ハッシュ内で統一すること。
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
