AllCops:
  # 継承先のプロジェクトでRuby/Railsのバージョンを設定してください。
  # TargetRubyVersion: x.x
  # TargetRailsVersion: x.x
  Exclude:
    - './db/schema.rb'
    - './db/migrate/**/*'

Rails:
  Enabled: true

# 以下のメソッドはパフォーマンスや可読性の観点からブロック行数が長くても良しと判断し、
# メソッド名で除外設定をしている。
# RailsのRouterよりnamespace/resource/resources
# FactoryGirlのdefine/factory
# Rspecのdescribe/it/feature/context/shared_context
Metrics/BlockLength:
  CountComments: false
  ExcludedMethods:
    - namespace
    - resource
    - resources
    - task
    - define
    - factory
    - describe
    - it
    - feature
    - context
    - shared_context

Metrics/BlockNesting:
  CountBlocks: false

Metrics/ClassLength:
  CountComments: false

Metrics/MethodLength:
  CountComments: false

Metrics/ModuleLength:
  CountComments: false

Metrics/ParameterLists:
  CountKeywordArgs: true

# 日本人向けプロダクトで日本語コメント禁止は厳しすぎるので。
# また、sdocでYARD形式のコメントを書くため記号を許容したい。
Style/AsciiComments:
  Enabled: false

# Caseに対してWhenをインデントしないこと。
Style/CaseIndentation:
  IndentOneStep: false

# CommentIndentationはシャープのインデント揃えをチェックするが、
# 処理をコメントアウトした場合には処理自体のインデントを揃えた方が綺麗な場合があるためOFF。
Style/CommentIndentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# 自作クラスには出来るだけコメントを書いて欲しい。
# Railsのように規約によってある程度クラスの意味はわかる場合、
# 親クラスに :nodoc: all とコメントを入れる事でこの警告は消せます。
Style/Documentation:
  Enabled: true

# メソッドチェーンを書く際、ドットは次の行の先頭に書くこと。
# irbやpryで実行しづらいデメリットはあるが、この方が可読性が高くコメントアウトもしやすいため。
Style/DotPosition:
  EnforcedStyle: leading

# 文字列のフォーマットは、format/sprintf/percentで行うこと。
Style/FormatString:
  SupportedStyles:
    - format
    - sprintf
    - percent

# ハッシュのキー指定方法はruby1.9の文法を利用し、ハッシュ内で統一すること。
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# 演算子の前後には半角スペースを入れること。
Style/SpaceAroundOperators:
  AllowForAlignment: true
